models:
  - model: ./models/R1-Llama3-8B
    parameters:
      weight: 1.0
      density: 0.1
merge_method: della_linear
base_model: ./models/Llama3-8B
tokenizer:
  source: ./models/R1-Llama3-8B
parameters:
  int8_mask: true
  normalize: true
  lambda: 1.1
  epsilon: 0.05
dtype: float16
chat_template: null