models:
  - model: ./models/R1-Llama3-8B
    parameters:
      weight: 0.1
  - model: ./models/I-Llama3-8B
    parameters:
      weight: 0.9
tokenizer:
  source: ./models/R1-Llama3-8B
merge_method: linear
dtype: float16
