base_model: ./models/Llama3-8B
chat_template: null
dtype: float16
merge_method: della_linear
models:
- model: ./models/R1-Llama3-8B
  parameters:
    density: 0.7
    weight: 1.0
parameters:
  epsilon: 0.2
  int8_mask: true
  lambda: 1.1
  normalize: true
tokenizer:
  source: ./models/R1-Llama3-8B
