base_model: ./models/Llama3-8B
chat_template: null
dtype: float16
merge_method: breadcrumbs
models:
- model: ./models/R1-Llama3-8B
  parameters:
    density: 0.9
    gamma: 0.01
    weight: 1.0
parameters:
  int8_mask: true
  normalize: true
tokenizer:
  source: ./models/R1-Llama3-8B
