base_model: ./models/I-Llama3-8B
dtype: float16
merge_method: ties
models:
- model: ./models/R1-Llama3-8B
  parameters:
    density: 0.5
    weight: 1.0
parameters:
  int8_mask: true
  normalize: true
tokenizer:
  source: base
