chat_template: null
dtype: float16
merge_method: linear
models:
- model: ./models/R-Phi4
  parameters:
    weight: 0.7
- model: ./models/I-Phi4
  parameters:
    weight: 0.3
tokenizer:
  source: ./models/R-Phi4
