base_model: ./models/I-Phi4
chat_template: null
dtype: float16
merge_method: breadcrumbs
models:
- model: ./models/R-Phi4
  parameters:
    density: 0.7
    gamma: 0.01
    weight: 1.0
parameters:
  int8_mask: true
  normalize: true
tokenizer:
  source: ./models/R-Phi4
