base_model: ./models/I-Phi4
dtype: float16
merge_method: dare_linear
models:
- model: ./models/R-Phi4
  parameters:
    density: 0.3
    weight: 1.0
parameters:
  int8_mask: true
  normalize: true
tokenizer:
  source: base
