base_model: ./models/Qwen2.5-14B
chat_template: null
dtype: float16
merge_method: ties
models:
- model: ./models/R1-Qwen2.5-14B
  parameters:
    density: 0.5
    weight: 1.0
parameters:
  int8_mask: true
  normalize: true
tokenizer:
  source: ./models/R1-Qwen2.5-14B
