dtype: float16
merge_method: linear
models:
- model: ./models/R1-Qwen2.5-14B
  parameters:
    weight: 0.1
- model: ./models/I-Qwen2.5-14B
  parameters:
    weight: 0.9
tokenizer:
  source: ./models/I-Qwen2.5-14B
