base_model: ./models/Qwen2.5-14B
dtype: float16
merge_method: dare_linear
models:
- model: ./models/R1-Qwen2.5-14B
  parameters:
    density: 0.3
    weight: 1.0
parameters:
  int8_mask: true
  normalize: true
tokenizer:
  source: ./models/R1-Qwen2.5-14B
