base_model: ./models/I-Qwen2.5-14B
dtype: float16
merge_method: ties
models:
- model: ./models/R1-Qwen2.5-14B
  parameters:
    density: 0.1
    weight: 1.0
parameters:
  int8_mask: true
  normalize: true
tokenizer:
  source: base
